### ISSUE TITLE
Ask  a little question

### ISSUE THREAD

**Issue by LuoJiaji** [SkalskiP/ILearnDeepLearning.py#1]
Thanks for your code
when I run the code in Advanced Visualisation of Lorenz Attractor
I save the code in python file and change the code
`anim.save('lorenz_attractor.gif', dpi=80, writer='imagemagick')
`
to 
`plt.show()`

When  I run the code by CMD 
It gives me a blank plot
I don't know why...

**Comment by SkalskiP** [comment]
I am very sorry, I have not followed the issues so far.  Did you manage to solve this problem?
