### ISSUE TITLE
In  01_mysteries_of_neural_networks/03_numpy_neural_net, file "Numpy deep neural network.ipynb" not showing up in github.

### ISSUE THREAD

**Issue by anitoanto** [SkalskiP/ILearnDeepLearning.py#10]
## "Numpy deep neural network.ipynb"
The file has error in ipynb structure. The file is not showing in github as expected. The fixed file is submitted as pull request.

**Comment by anitoanto** [comment]
To see the error, try opening Numpy deep neural network.ipynb file inside github.

**Comment by SkalskiP** [comment]
Looks like your changes fixed the problem. Thank you so much for your contribution :)
