### ISSUE TITLE
can not see the formula in the step "Single layer forward propagation step"

### ISSUE THREAD

**Issue by airsimonhan** [SkalskiP/ILearnDeepLearning.py#3]
maybe markdown bug, can't see the formula below,
 $$\boldsymbol{Z}^{[l]} = \boldsymbol{W}^{[l]} \cdot \boldsymbol{A}^{[l-1]} + \boldsymbol{b}^{[l]}$$

**Comment by SkalskiP** [comment]
Thank you very much for catching this bug. It looks like it's a issue in markdown handling.  I have broken the equations so that they are in separate cells and the error seems to have disappeared. Thank you.
